.TH SDKVM 1

.SH NAME
sdkvm fetch \- fetch SDK versions from remote source

.SH SYNOPSIS
.B sdkvm fetch
.RI [ SDK ]

.SH DESCRIPTION
Fetch SDK versions from remote source and cache them for future uses. Downloads all avaialbel versions from remote sources and makes them available to install.
.PP
If no SDK is provided them all versions for all SDKs are fetched.

.SH SEE ALSO
sdkvm install
sdkvm enable
sdkvm list
