.Dd December 21, 2025
.Dt SDKVM-DISABLE 1
.Os

.Sh NAME
.Nm sdkvm disable
.Nd disable a SDK.

.Sh SYNOPSIS
.Nm
.Ar SDK
.Op Ar VERSION

.Sh DESCRIPTION
.Nm
Disable SDK version by removing SDK binaries from the PATH variable.\&
The change is visible in current terminal session and all children processes.\&
If no version is provided the newest installed version is used.
.Pp
Disabled SDK version may be persisted using \fI--save\fR option.

.Sh ARGUMENTS
.Bl -tag -width Ds
.It Fl s , Fl -save
Save disabled SDK so it is not enabled automatically during system startup.

.Sh SEE ALSO
.Xr sdkvm-enable 1 ,
.Xr sdkvm-list 1
