.TH SDKVM 1
." Sources on writing man pages:
." - basic format: http://www.linuxhowtos.org/System/creatingman.htm
." - syopsis: https://unix.stackexchange.com/a/425026
."

.SH NAME
sdkvm \- manage different versions of Software Development Kits.

.SH SYNOPSIS
.B sdkvm
.RB [ \-\-version | \-\-update | \-\-help ]
.br
.B sdkvm
.RB [ \-\-debug ]
.RB [ \-\-no\-pretty ]
.I COMMAND
.RI [ OPTS ]

.SH DESCRIPTION
Sdkvm manages different Software Development Kits (SDK). It is designed to handle all kinds of SDKs and add no overhead to the terminal startup time.
.PP
Sdkvm uses cached information on available SDKs. The list od SDK avaialble versions can be easily updated.
.PP
In comparison with nvm, rvm or sdkman it adds little overhead to the terminal startup time and it is not dedicated to any specific SDK.
.PP
Source: \fIhttps://github.com/pmendelski/sdkvm\fR

.SH OPTIONS
Lisf of options available in all sdkvm commands:
.TP
.BR \-v ", " \-\-version\fR
Print the sdkvm version.
.TP
.BR \-u ", " \-\-update\fR
Update the sdkvm.
.TP
.BR \-h ", " \-\-help\fR
Print the manual.
.TP
.BR \-d ", " \-dd ", " \-\-debug\fR
Increase log verbosity. Multiple occurrences (\fI\-d\fR \fI\-d\fR or \fI\-dd\fR) increases the verbosity even more.
.TP
.BR \-p ", " \-\-no-pretty\fR
Disable pretty printing. Remove colors and icons from logs.

.SH COMMANDS
.TP
.B list
List SDKs.
.TP
.B install
Install a SDK.
.TP
.B unintsall
Uninstall a SDK.
.TP
.B update
Install and enable the newest SDK version.
.TP
.B fetch
Fetch remote SDK versions.
.TP
.B enable
Enable an installed version of SDK.
.TP
.B disable
Disable a previousle enabled SDK version.
.TP
.B version
Print enabled version of SDK.
