.TH SDKVM 1

.SH NAME
sdkvm index \- index remote SDK versions

.SH SYNOPSIS
.B sdkvm index
.RI [ SDK ]

.SH DESCRIPTION
Index SDK versions from remote source and cache them for future uses. Downloads all avaialbel versions from remote sources and makes them available to install.
.PP
If no SDK is provided them all versions for all SDKs are fetched.

.SH SEE ALSO
sdkvm install
sdkvm enable
sdkvm list
