#!/bin/bash -e

echo "NAME"
echo "  sdkvm - Ubuntu SDK version manager."
echo "  Source: https://github.com/pmendelski/sdkvm"
echo ""
echo "SYNOPSIS"
echo "  sdkvm COMMAND [OPTION]..."
echo "  sdkvm COMMAND --help"
echo ""
echo "COMMANDS"
echo "  selfupdate            Update sdkvm from the github repository"
echo "  install SDK [VERSION] Install sdk. If no version is specified the newest is picked."
echo "  switch SDK [VERSION]  Switch sdk version. If no version is specified the newest is picked."
echo "  delete SDK [VERSION]  Delete sdk. If no version is specified all versions are removed."
echo "  list [SDK]            List sdk versions. If ne version is defined all sdks are listed."
echo ""
